### ISSUE TITLE
Clarification on usage with wrangler 2

### ISSUE THREAD

**Issue by thepassle** [worker-tools/location-polyfill#1]
Im not entirely sure how worker-tools is tied exactly to cloudflare, I just tried upgrading my project (which uses `@worker-tools/location-polyfill`) to wrangler 2, and I now get the following error:

```
  {
    text: 'Received a bad response from the API',
    notes: [
      {
        text: 'Uncaught TypeError: Invalid URL string.\n' +
          '  at line 64 in WorkerLocationPolyfill\n' +
          '  at line 51 in defineProperty\n' +
          '  at line 102 in node_modules/@worker-tools/location-polyfill/index.js\n' +
          '  at line 8 in __init\n' +
          '  at line 4356 in dist/worker/index.js\n' +
          '  at line 8 in __init\n' +
          '  at line 7061\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

Removing the import for `import '@worker-tools/location-polyfill'` seems to fix the problem. Am I correct to assume that the polyfill is no longer required, and is just built-in now? Or am I missing something? Thanks!

Repro: `echo "import '@worker-tools/location-polyfill';" > index.js && npx wrangler dev`

**Comment by qwtel** [comment]
Haven't tried with wrangler 2 yet. Could be the issue. Based on the error, could also be a bad value for the worker location. Make sure you have a fully qualified URL like so in the wrangler.toml
```toml
[vars]
  WORKER_LOCATION = 'http://localhost:8787'
```

**Comment by thepassle** [comment]
It seems like `self[WORKER_LOCATION]` is always true:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/17054057/167441243-36616dd1-cdd1-4bc5-b505-acc6b771e768.png">

even if I set the `[vars]` in the wrangler.toml, it never evaluates to the `self.process?.env?.[WORKER_LOCATION]`

**Comment by qwtel** [comment]
You're right. Now I'm not sure how this worked in the first place. Try with 0.4.1.
